### ISSUE TITLE
array()の書き方

### ISSUE THREAD

**Issue by cilenn** [topherbuckley/greenscrape#1]
$cybozu_headers = array();
$cybozu_headers[0] =  "レコード番号";
$cybozu_headers[1] =  "営業担当者";
$cybozu_headers[2] =  "企業名";

---

この様にも書けます。シンプル。
↓ 
$cybozu_headers = [];
$cybozu_headers = [ "レコード番号", "営業担当者", "企業名" ];

**Comment by topherbuckley** [comment]
了解です。ありがとうございます！PHPは初めてですので、そんなシンプルの書き方はまだ習ってないですよね。ありがとうございます。

2015-11-19 14:21 GMT+09:00 cilenn notifications@github.com:

**Comment by cilenn** [comment]
$arr = []; の書き方は新しい書き方です。(PHP 5.4〜)
Laravelは推奨しています。
http://php.net/manual/en/language.types.array.php

phpは書き方がいろいろあるので、始めは混乱するかも。

**Comment by topherbuckley** [comment]
多いですよね。了解です。これからその書き方を使います。

2015-11-19 14:30 GMT+09:00 cilenn notifications@github.com:
